[tool.poetry]
name = "confz"
version = "1.2.0"
description = "ConfZ is a configuration management library for Python based on pydantic."
license = "MIT"
authors = ["ZÃ¼hlke"]
readme = "README.md"
homepage = "https://github.com/Zuehlke/ConfZ"
repository = "https://github.com/Zuehlke/ConfZ"
documentation = "https://confz.readthedocs.io"
keywords = ["Configuration Management", "Config Management"]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.8.2"
PyYAML = "^5.4.1"
python-dotenv = "^0.19.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
Sphinx = "^4.2.0"
pytest-cov = "^3.0.0"
pytest-asyncio = "^0.16.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
