[tool.poetry]
name = "confz"
version = "0.3.0"
description = "ConfZ is a configuration management library for Python based on pydantic."
authors = ["ZÃ¼hlke"]

[tool.poetry.dependencies]
python = "^3.7"
pydantic = "^1.8.2"
PyYAML = "^5.4.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
coverage = "^6.0.2"
Sphinx = "^4.2.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
